var GAME_LEVELS = [
  ["                                                                                                                                                ",
  "                                                                                                                                                ",
  "                                                                                                                                                ",
  "                                                                                                                                                ",
  "                                                                                                                                                ",
  "                                                                                                                                                ",
  "                                                                 xxxxxx                                                                         ",
  "                                     v     xxx      xxxx         xx!!!!xx                                                                       ",
  "                 v                                          >    x!!!!!!x                                                                       ",
  "                                 o            o                  xx!!!!xx                                                                       ",
  "                     yyyyyy              xxxxx    ===     v         !!                                                                          ",
  "             o        yyyy                                                                                                                      ",
  "             o              >                     o        xxxx                                                                                 ",
  "             xxx    #            xxxxx   !!!!                                                                                                   ",
  "                                        xxxxx                 o o       x                                                                        ",
  "                   xxxx    >                     #                           x                                                                  ",
  "    @              ===                                                       x                                                                  ",
  "  xxxxxxx  !!!!  xxxxxxxxxxxxxx       xxxxxxxxxxxxxxx     xxxxxxx!!!!xxxxxxxxx                                                                  ",
  "                              x       x             x     x                                                                                     ",
  "                              x!!!!!!!x             x!!!!!x                                                                                     ",
  "                              x!!!!!!!x             x!!!!!x                                                                                     ",
  "                              xxxxxxxxx             xxxxxxx                                                                                     ",
  "                                                                                                                                                ",
  "                                                                                                                                                "],
  ["                                                                                                                                                ",
   "                                                                                                                                                ",
   "                                                                                                                                                ",
   "                            !!!!!!!                                                                                                             ",
   "                >            !!!!!     yyyyy           v                                                                                        ",
   "                              !!!                           v                                                                                   ",
   "     yyyyy                                      o                                                                                               ",
   "      yyy                                          xxxx                     >                                                                   ",
   "                                      #                         yyyy                                                                            ",
   "             !!!                                                                                                                                ",
   "            xxxxx     #         o    xxxx                                                                                                       ",
   "                               o                          o                                                                                     ",
   "                      o                                 xxxxx       o                                                                           ",
   "      @               o                    !!!!!                    o                                                                           ",
   "      xx      v      xxxxx           >xxxx        xxxxx                xxxx                                                                     ",
   "     xxxx                             xxxx                                                                                                      ",
   "  !!!xxxx!!!                !!!!!!   xxxxx                                                                                                      ",
   "  xxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxx!!!!xxxxxxxxx                                                                   ",
   "                                                                                                                                                ",
   "                                                                                                                                                ",
   "                                                                                                                                                "],
["              v                          v                      v        o                                                                      ",
"    !!!!!!!                                   !!!!!!!!!!!!                o                                                                      ",
"     !!!!!                          >          !!!!!!!!!!                 o                                                                      ",
"      !!!             o            !            !!!!!!!!              !   o   !                                                                  ",
"       !              o           !!!             !!!! xxxxxx         !   o   !                                                                  ",
"                                 !!!!!             v                  !xxxxxxx!                                                                  ",
"               o                   >                         #        !!!!!!!!!                                                                  ",
"                                                                       >                                                                         ",
"                      #                                                >           !                                                             ",
"                     xxxx          o                 >    xxxxx                    !                                                             ",
"                                              #                   o                !                                                             ",
"                           !             o                    xxxxxx               !                                                             ",
"          xx              !!!            o         >    !                         !!!                                                            ",
"  !!!    !!!   v         !!!!!           o              !          !!            !!!!!                                                           ",
"  !!!    !!!            !!!!!!!         xxxx           !!!        !!!!          !!!!!!!                                                          ",
"  !!!  @ !!!           !!!!!!!!!                    !!!!!!!!!!!!!!!!!!!      !!!!!!!!!!                                                          ",
"  xxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxx!!!!!!!xxxxxxx!!!!xxxxxxx!!!!!!!!!!!                                                     ",
"                                 !!!!!!!                                                                                                         ",
"                                 !!!!!!!                                                                                                         ",
"                                                                                                                                                 "],
["                                                                                                                                                 ",
"        oooooo     oooooo   oooooooooooooo    oooo      oooo        oooooo                     oooooo  ooooooooo   ooooooooooo        oooooo     ",
"         ooooo     ooooo   oooooooooooooooo   oooo      oooo         oooooo                   oooooo   ooooooooo   oooooo ooooo       oooooo     ",
"          oooo     oooo    oooo        oooo   oooo      oooo          oooooo                 oooooo       ooo      oooooo  ooooo      oooooo     ",
"           ooooooooooo     oooo        oooo   oooo      oooo           oooooo               oooooo        ooo      oooooo   ooooo     oooooo     ",
"            ooooooooo      oooo        oooo   oooo      oooo            oooooo      o      oooooo         ooo      oooooo    ooooo    oooooo     ",
"              ooooo        oooo        oooo   oooo      oooo             oooooo    ooo    oooooo          ooo      oooooo     ooooo   oooooo     ",
"               ooo         oooo        oooo   oooo      oooo              oooooo  ooooo  oooooo           ooo      oooooo      ooooo  oooooo     ",
"               ooo         oooooooooooooooo   oooooooooooooo               ooooooooooooooooooo         ooooooooo   oooooo       ooooo oooooo     ",
"               ooo          oooooooooooooo     oooooooooooo                 ooooooo   ooooooo          ooooooooo   oooooo        ooooooooooo     ",
"                                                                                                                                                 ",
"               xxxxxxxxx       xxxxxxx            xxxxxxx                   xxxxxxx    xxxxxxx          xxxxxxx     xxxxxxxx        xxxxxxx      ",
"                                                                                                                                                 ",
"                                                                                                                                                 ",
"                                                                                                                                                 ",
"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
"    >                       >                        >                      >                        >                      >                    ",
"              >                        >                       >                        >                      >                        >        ",
"    >                       >                        >                      >                        >                      >                    "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
